#!/usr/bin/env python3
"""Hermes SRC quality gate.

Reads a probe_results.tsv generated by Hermes SRC workflows and emits a
conservative submit/no-submit decision. This is a heuristic gate; Hermes main
agent still performs the final reasoning and report writing.
"""
from __future__ import annotations

import argparse
import csv
import json
import re
from pathlib import Path
from typing import Dict, List

SENSITIVE_PATTERNS = [
    ("pii", re.compile(r"姓名|手机号|身份证|学号|工号|邮箱|email|mobile|phone|idcard|identity", re.I)),
    ("auth", re.compile(r"token|authorization|session|jwt|ticket|secret|appsecret|apikey|access[_-]?key", re.I)),
    ("business", re.compile(r"订单|支付|金额|余额|成绩|课程|申请|流程|审批|借阅|住址|部门|组织|appName|serviceName", re.I)),
    ("sql_error", re.compile(r"SQLSyntaxErrorException|SQLException|mysql|oracle|postgres|mapper\.java|Unknown database|syntax error", re.I)),
    ("upload", re.compile(r"fileUrl|resId|ossId|genName|downloadUrl|upload.*success|上传成功", re.I)),
    ("rce", re.compile(r"uid=|gid=|root:|/bin/bash|Windows IP Configuration", re.I)),
]

NEGATIVE_PATTERNS = re.compile(
    r"Token失效|token信息不存在|FA_INVALID_SESSION|未登录|请登录|login|Login|登录|404 Not Found|403 Forbidden|Error Page|unexpected user service|empty|^$",
    re.I,
)


def read_rows(path: Path) -> List[Dict[str, str]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    first = text.splitlines()[0] if text.splitlines() else ""
    if "\t" in first:
        reader = csv.DictReader(text.splitlines(), delimiter="\t")
        if reader.fieldnames and any(name in ("method", "url", "status") for name in reader.fieldnames):
            return [dict(r) for r in reader]
        # headerless legacy probe_results.tsv shape
        fields = ["method", "url", "status", "size", "content_type", "hash", "title", "sensitive_hit", "body_path"]
        rows = []
        for line in text.splitlines():
            parts = line.split("\t")
            rows.append({fields[i]: parts[i] if i < len(parts) else "" for i in range(len(fields))})
        return rows
    return []


def classify(row: Dict[str, str]) -> Dict[str, str]:
    blob = " ".join(str(row.get(k, "")) for k in row)
    status = str(row.get("status", ""))
    size = int(str(row.get("size", "0") or "0").split()[0]) if re.match(r"^\d+", str(row.get("size", "0"))) else 0
    hits = [name for name, pat in SENSITIVE_PATTERNS if pat.search(blob)]
    negative = bool(NEGATIVE_PATTERNS.search(blob)) or status in {"000", "401", "403", "404"} or size == 0
    if hits and status.startswith("2") and not (set(hits) == {"business"} and negative):
        decision = "NEED_REVIEW"
    elif negative:
        decision = "DO_NOT_SUBMIT"
    else:
        decision = "LOW_SIGNAL"
    return {"url": row.get("url", ""), "status": status, "size": str(size), "hits": ",".join(hits), "decision": decision, "body_path": row.get("body_path", row.get("body", ""))}


def main() -> int:
    parser = argparse.ArgumentParser(description="Gate SRC probe results")
    parser.add_argument("probe_results", help="probe_results.tsv path")
    parser.add_argument("--target-profile", default="", help="Optional target_profile.md for duplicate hints")
    parser.add_argument("--out", default="", help="Write final gate markdown")
    args = parser.parse_args()

    rows = read_rows(Path(args.probe_results))
    classified = [classify(r) for r in rows]
    review = [r for r in classified if r["decision"] == "NEED_REVIEW"]
    low = [r for r in classified if r["decision"] == "LOW_SIGNAL"]
    profile_text = Path(args.target_profile).read_text(encoding="utf-8", errors="replace") if args.target_profile and Path(args.target_profile).exists() else ""

    verdict = "DO_NOT_SUBMIT"
    reason = "No unauthenticated sensitive data, exploit capability, or high-confidence impact was detected by the heuristic gate."
    if review:
        verdict = "NEED_MORE_EVIDENCE"
        reason = "Potential sensitive/exploit indicators found; manual verification and duplicate/root-cause review required before reporting."

    md = []
    md.append("# SRC Quality Gate\n")
    md.append(f"Verdict: {verdict}\n")
    md.append(f"Reason: {reason}\n")
    md.append(f"Rows analyzed: {len(rows)}\n")
    md.append(f"Review candidates: {len(review)}\n")
    md.append(f"Low-signal candidates: {len(low)}\n")
    if profile_text:
        md.append("Target profile: loaded\n")
    md.append("\n## Review candidates\n")
    if review:
        for r in review[:50]:
            md.append(f"- {r['status']} {r['url']} hits={r['hits']} body={r['body_path']}\n")
    else:
        md.append("- none\n")
    md.append("\n## Low signal / negative examples\n")
    for r in classified[:100]:
        if r["decision"] != "NEED_REVIEW":
            md.append(f"- {r['decision']} {r['status']} {r['url']} hits={r['hits']}\n")
    output = "".join(md)

    if args.out:
        Path(args.out).write_text(output, encoding="utf-8")
    print(json.dumps({"verdict": verdict, "rows": len(rows), "review_candidates": len(review), "out": args.out}, ensure_ascii=False))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
